### PR TITLE
Fix #531

### LINKED ISSUE #531: The built in validators(phone, email etc.) are validating optional parameters
Testcase to reproduce the error:

``` php
/**
 * @param string $name
 * @param string $phone 
*/
public function post($name, $phone = "") 
{
...
}
```

Now if I post phone parameter as an empty string eg.:

``` json
{
  "name": "John Doe",
  "phone": "",
}
```

The phone validator still try to validate the value, and obviously throws an error:

```
Bad Request: Invalid value specified for `phone`. Expecting phone number, a numeric value with optional `+` prefix
```

### PR DESCRIPTION
**Pull request by letsbyteit**
Fix validating empty optional parameters.

@csiszarattila Here comes the fix for the validator-issue.

### CODE REVIEW

**Comment by letsbyteit** [comment]
I just fixed another validator bug. You might have a look at this, @Arul-.

**Comment by ddrager** [comment]
Fine with me @letsbyteit!

**Comment by Arul-** [comment]
@letsbyteit can you make the pull request against the v3 branch?

**Comment by Arul-** [comment]
Let me close this pull request, please make a pull request against v3 branch

**Comment by grosch** [comment]
@Arul- Did this get merged in?  I have this issue as well.

Any idea when something newer than 3.0.0-RC6 will be posted?  It's been years man :)

**Comment by Arul-** [comment]
@grosch cad72d0cb364951b2ae85f066494ddc4f17e52c0 is fixing it!

**Pull request closed without merging**
