### PR TITLE
allowing Restler to return an error if user authentication details are wrong and...

### PR DESCRIPTION
**Pull request by HomelessGruesomeMoose**
... resource has hybrid access.

I'm not sure of the impact this will have for someone who throws exceptions in __isAllowed() and expects them to be ignored when a resource has hybrid access.

### CODE REVIEW

**Comment by tomahock** [comment]
This bothers me!
On __isAllowed i'm validating some token on http headers. If valid token, return ok. Else throw new rest exception.
But if there is no token i'm returning false, so after in my resource class i can call $this->restler->_authenticated.

Is there any way arround?

**Comment by HomelessGruesomeMoose** [comment]
I have the same use-case as you. I allow multiple types of authentication and also allow anonymous browsing but I want to tell the end-user if their credentials are invalid. That's why I created this pull request. Unfortunately, I now have to maintain a fork to do so.

**Comment by Arul-** [comment]
I completely get your point and agree that this has to be solved. :+1: 

Let me apologize for the delay in looking into it so far!

------------
Let me share my views on this,

I think we have to improve the RestException class to add a property to force throwing exception even for hybrid mode

This way it becomes the responsibility of the Auth class to see if the user is actively attempting to authenticate  and set the force property to true in that case.

What do you guys think?

**Comment by tomahock** [comment]
That will work for me! :+1:

**Comment by Arul-** [comment]
Waiting to hear from @HomelessGruesomeMoose

**Comment by HomelessGruesomeMoose** [comment]
I await to see the implementation but in theory, I agree.

**Comment by yannis-rossetto** [comment]
Hello @Arul-, 

Any news about this feature request and its implementation ?

**Comment by Arul-** [comment]
When you have some credentials for authentication but find them invalid, now you have a way to force throwing an exception.

RestException supports a details parameter, which can now includes `forceException` key with the value `true` to make sure the exception is thrown even in hybrid mode

```php
throw new RestException(401, 'Authentication Failed', array('forceException' => true));
```

Just do the above from your auth class

**Comment by yannis-rossetto** [comment]
Hello @Arul- 

Thanks for you patch. I've tested it today but it does not work in my case.

I've got 2 authentication classes (TokenAuthentication and BasicAuthentication).
My API will first check the Token, then the Basic Auth if necessary.

So, if I use the Basic Auth with wrong credentials, my TokenAuthentication will return false and then Restler.php (line 963) will store the default exception (with no forceException). 
Then, my Basic Auth class will throw an exception with forceException === true because of wrong credentials.

However, this last exception will not be stored (Restler.php line 962) and **my forceException will not be taken into account in Restler.php at line 972.**

Maybe the forceException has to be stored if one of the exceptions catched line 961 has the option.
What do you think about that ?

**Comment by Arul-** [comment]
@yannis-rossetto understood. I'm also thinking use of forceException in details array is a bad idea

I'm thinking of creating new exception class extending `RestException`.  It can be named `InvalidAuthCredentials`.

When we need to throw an exception that needs to be forced, we can use it instead of `RestException`

**Comment by Arul-** [comment]
@yannis-rossetto please try the new solution in the above commit and let us know!

**Pull request closed without merging**
