### PR TITLE
Swagger fixes for Restler v2\Explorer implementation

### PR DESCRIPTION
**Pull request by richardeaxon**
When using Explorer v2 there are some inconsistencies to the old Resources implementation. The first issue is that the request_data optional fields appears in the generated swagger.json. The second issue is that the useUrlBasedVersioning config option is not honoured when building the swagger.json, thus the swagger.json paths do not have the API version in the path.

use Luracast\Restler\Restler;
use Luracast\Restler\Explorer\v2;
use Luracast\Restler\Defaults;

Defaults::$useUrlBasedVersioning = true;

$r = new Restler();
$r->setAPIVersion(1);
$r->addAPIClass("Explorer", "explorer2");

### CODE REVIEW

**Comment by Arul-** [comment]
Thanks for contributing @richardeaxon Will check it out!

**Comment by Arul-** [comment]
@richardeaxon please make this pull request against the v5 branch

**Comment by richardeaxon** [comment]
Ok, changed the base to v5 but there is now a merge conflict. Please fix as you require write access. Thanks.

**Comment by Arul-** [comment]
Thanks! I manually merged it to v5 branch. See 54972247fb84def9ffa418f61d1c6efd9f7e8c2d

**Pull request closed without merging**
