### PR TITLE
Remove powered header

### PR DESCRIPTION
**Pull request by tomahock**
If production mode remove X-Powered-By header

### CODE REVIEW

**Comment by roydekleijn** [comment]
As there are no conflicts.. can this be merged ?

**Comment by Arul-** [comment]
I would like to let the header live through production mode

**Comment by selenium-in-action** [comment]
It can be a security thing....
If people know it's vulnerabilities..

**Comment by Arul-** [comment]
@selenium-in-action Lets come up with a Defaults config to change it to what the API developer wants

**Pull request closed without merging**
