### PR TITLE
Update README.me - remove version string

### PR DESCRIPTION
**Pull request by jk**
This is just a small PR to remove the "Release Candidate 5" version string from the headline.

### CODE REVIEW

**Comment by Arul-** [comment]
Release Candidate 5 (RC5) stands there for a purpose. Why do you want to remove it?

**Comment by jk** [comment]
@Arul- Sorry, my bad, I just saw the commit https://github.com/Luracast/Restler/commit/e2b0b8e1974f5584b37a567f4cc127578ce473c5 and saw that this commit was tagged as `3.0.0` so I thought this was declared a final version. Since this is not the intended final 3.0.0 release (I just saw the RC6 tag on the `v3` branch) - you should remove that `3.0.0` tag, since composer relies on that: https://packagist.org/packages/luracast/restler#3.0.0

Version order for composer is 0.x → 1.0.0-alphaX → 1.0.0-betaX → 1.0.0-RCX → 1.0.0 → 1.0.0-plX → 1.0.1 → …

So you can close this PR.

**Comment by andytruong** [comment]
I am also confused, not sure why version 3.0. is released before RC6 https://github.com/Luracast/Restler/releases

**Comment by Arul-** [comment]
3.0.0 is the official stable release of Restler version 3 which is currently pointing to RC5 (in master brach)

RC6 is still under construction (in v3 branch). Once RC6 becomes official, it will be available in master branch and 3.0.0 will point to it.

**Pull request closed without merging**
