### PR TITLE
Features/swagger2.0

### PR DESCRIPTION
**Pull request by letsbyteit**
I've made some additions to support Swagger 2.0. I'm not quite sure, whether it fits for your needs. Just have a look.

### CODE REVIEW

**Comment by flumenhaggen** [comment]
there is any plan to merge this into the next release?
I need support for 2.0 too. I'll be testing this branch and leave feedback.

**Comment by Arul-** [comment]
@flumenhaggen we will be merging an improved version soon!

**Comment by doratias** [comment]
@flumenhaggen did you have a chance to test it?

**Comment by flumenhaggen** [comment]
@doratias nops. I end up using a separate swagger file for the specification. I make an advanced use of schema for models and need to be fine grained.

**Pull request merged**
